import day1Native from './native-day-1.js';import day2Native from './native-day-2.js';import{realtimeSync}from'./realtimeSync.js';import React,{useEffect,useState} from 'react';import{createRoot}from'react-dom/client';import'./style.css';
const K='human-school-submissions-v1',CK='human-school-submission-config-v1';
const seed=[
{id:'seed-a',name:'Priya S.',role:'Operations',idea:'Turn weekly status updates into a leadership brief.',prompt:'Summarize these updates.',category:'needs-work',reviewed:true},
{id:'seed-b',name:'Rohan M.',role:'Sales',idea:'Prepare before every client call using CRM notes.',prompt:'Act as an account strategist. Using the CRM notes and last three emails, give me the client goal, two risks, three questions, and a 60-second opening.',category:'exemplar',reviewed:true},
{id:'seed-c',name:'Neha K.',role:'HR',idea:'Create interview scorecards from role requirements.',prompt:'Build a scorecard for this role with five criteria and a 1–5 rubric.',category:'discuss',reviewed:true}
];
const read=()=>{try{return JSON.parse(localStorage.getItem(K))||seed}catch{return seed}};const write=x=>localStorage.setItem(K,JSON.stringify(x));
const merge=(a,b)=>{let m=new Map(a.map(x=>[x.id,x]));b.forEach(x=>m.set(x.id,{...(m.get(x.id)||{}),...x}));return [...m.values()]};
const defaultDeadline=()=>{let d=new Date();d.setHours(23,59,0,0);return d.toISOString()};
const readConfig=()=>{try{return JSON.parse(localStorage.getItem(CK))||{isEnabled:true,deadlineTimestamp:defaultDeadline()}}catch{return {isEnabled:true,deadlineTimestamp:defaultDeadline()}}};
function useLiveConfig(){let[c,setC]=useState(readConfig());useEffect(()=>realtimeSync.subscribe(e=>{if(e.type==='SUBMISSIONS_CONFIG_UPDATE'&&e.config){setC(e.config);localStorage.setItem(CK,JSON.stringify(e.config))}}),[]);return[c,n=>{setC(n);localStorage.setItem(CK,JSON.stringify(n));realtimeSync.publish('submissions/config',{type:'SUBMISSIONS_CONFIG_UPDATE',config:n})}]}
function useLiveSubmissions(){let[x,setX]=useState(read());useEffect(()=>realtimeSync.subscribe(e=>{if(e.type==='SUBMISSION_STATE'&&Array.isArray(e.submissions))setX(v=>{let n=merge(v,e.submissions);write(n);return n});if(e.type==='NEW_SUBMISSION'&&e.submission)setX(v=>{let n=merge(v,[e.submission]);write(n);return n})}),[]);return[x,y=>{setX(y);write(y);realtimeSync.publish('submissions/state',{type:'SUBMISSION_STATE',submissions:y})}]}
function Shell({children}){return <>{children}<nav><a href="/day-1">Day 1</a><a href="/day-2">Day 2</a><a href="/submit">Submit</a><a href="/submissions">Review</a></nav></>}
const EMUW=9144000,EMUH=5143500;
const pos=e=>({left:(e.x/EMUW*100)+'%',top:(e.y/EMUH*100)+'%',width:(e.w/EMUW*100)+'%',height:(e.h/EMUH*100)+'%',transform:e.rot?'rotate('+e.rot+'deg)':undefined,background:e.bg||'transparent',border:e.border?e.border.width+'px '+(e.border.dash==='DASH'?'dashed':'solid')+' '+e.border.color:'none',borderRadius:e.radius,color:'#111',alignItems:e.valign==='MIDDLE'?'center':e.valign==='BOTTOM'?'flex-end':'flex-start',justifyContent:e.valign==='MIDDLE'?'center':e.valign==='BOTTOM'?'flex-end':'flex-start',textAlign:e.align});
function NativeSlide({elements,dark}){return <div className={"native-slide "+(dark?"dark":"")}>{elements.map(e=>e.kind==='image'?<img key={e.id} className="el" style={pos(e)} src={e.src}/>:e.kind==='video'?<div key={e.id} className="el video" style={pos(e)}>LIVE VIEWING</div>:<div key={e.id} className={'el shape '+(e.type||'').toLowerCase()} style={pos(e)}>{e.runs?.map((r,i)=><span key={i} style={{fontFamily:r.ff,fontSize:`calc(${r.fs/9.6} * var(--slide-vw))`,fontWeight:r.b?700:400,fontStyle:r.i?'italic':'normal',textDecoration:r.u?'underline':'none',color:r.c}}>{r.text}</span>)}</div>)}</div>}
function Deck({day}){let native=day===1?day1Native:day2Native,n=native.length,q=new URLSearchParams(location.search),start=Math.max(1,Math.min(n,+(q.get('slide')||1))),[s,setS]=useState(start);useEffect(()=>{let f=e=>{if(['ArrowRight',' ','PageDown'].includes(e.key))setS(x=>Math.min(n,x+1));if(['ArrowLeft','PageUp'].includes(e.key))setS(x=>Math.max(1,x-1))};addEventListener('keydown',f);return()=>removeEventListener('keydown',f)},[]);useEffect(()=>history.replaceState({},'',`/day-${day}?slide=${s}`),[s]);let dynamic=day===2&&s>=6&&s<=8,cat=s===6?'needs-work':s===7?'exemplar':'discuss',labels={'needs-work':['NEEDS WORK'],'exemplar':['EXEMPLAR'],'discuss':['DISCUSS']},[all]=useLiveSubmissions(),items=all.filter(x=>x.reviewed&&x.category===cat).slice(0,3);return <Shell><main className="stage" onClick={()=>setS(x=>Math.min(n,x+1))}><NativeSlide elements={native[s-1]} dark={(day===1&&[1,17,23,27,29,33,37].includes(s))||(day===2&&[1,10,12,16].includes(s))}/>{dynamic&&<section className="live"><div className="livehead"><b>{labels[cat][0]}</b><span>LIVE FROM /SUBMISSIONS</span></div><div className="cards">{items.length?items.map(x=><article key={x.id}><h3>{x.name}</h3><small>{x.role}</small><p>{x.prompt}</p></article>):<article className="empty">Review submissions to show them here.</article>}</div></section>}<div className="counter">{s} / {n}</div></main></Shell>}
function Submit(){let[done,setDone]=useState(false),[config]=useLiveConfig(),closed=!config.isEnabled||Date.now()>new Date(config.deadlineTimestamp).getTime();function go(e){e.preventDefault();let f=new FormData(e.currentTarget),x=read();x.push({id:crypto.randomUUID(),name:f.get('name'),role:f.get('role'),idea:f.get('idea'),prompt:f.get('prompt'),reviewed:false,category:''});write(x);realtimeSync.publish('submissions/new',{type:'NEW_SUBMISSION',submission:x[x.length-1]});setDone(true)}return <Shell><div className="page"><header><b>HUMAN SCHOOL</b><h1>Your Day 1 submission.</h1><p>Bring one real problem and the prompt you would use to solve it.</p></header>{closed?<div className="success">Submissions are closed. The facilitator will reopen the window when ready.</div>:done?<div className="success">Submitted. We'll review it for Day 2.</div>:<form onSubmit={go}><label>Name<input name="name" required/></label><label>Role<input name="role" required/></label><label>What is your idea?<textarea name="idea" required/></label><label>What prompt will you give?<textarea name="prompt" required/></label><button>Submit work →</button></form>}</div></Shell>}
function Review(){let[x,save]=useLiveSubmissions(),[config,setConfig]=useLiveConfig();let mark=(id,c)=>save(x.map(v=>v.id===id?{...v,reviewed:!!c,category:c}:v));return <Shell><div className="page wide"><header><b>FACILITATOR DASHBOARD</b><h1>Submissions.</h1><p>Review once. Approved work appears automatically on Day 2 slides 6–8.</p></header><div className="window"><b>SUBMISSION WINDOW</b><label className="toggle"><input type="checkbox" checked={config.isEnabled} onChange={e=>setConfig({...config,isEnabled:e.target.checked})}/> {config.isEnabled?'Open':'Closed'}</label><label>Deadline<input type="datetime-local" value={config.deadlineTimestamp.slice(0,16)} onChange={e=>setConfig({...config,deadlineTimestamp:new Date(e.target.value).toISOString()})}/></label><button className="subtle" onClick={()=>setConfig({...config,deadlineTimestamp:defaultDeadline()})}>Tonight 11:59</button></div><div className="filters"><a href="/day-2?slide=6">Open live review slides →</a><button className="subtle" onClick={()=>save(seed)}>Load demo data</button></div><div className="queue">{x.map(v=><article className="review" key={v.id}><div><h2>{v.name}</h2><small>{v.role}</small><h4>IDEA</h4><p>{v.idea}</p><h4>PROMPT</h4><blockquote>{v.prompt}</blockquote></div><div className="actions"><button className={v.category==='needs-work'?'on':''} onClick={()=>mark(v.id,'needs-work')}>Needs work</button><button className={v.category==='exemplar'?'on':''} onClick={()=>mark(v.id,'exemplar')}>Exemplar</button><button className={v.category==='discuss'?'on':''} onClick={()=>mark(v.id,'discuss')}>Discuss</button><button onClick={()=>mark(v.id,'')}>Hide</button></div></article>)}</div></div></Shell>}
function App(){let p=location.pathname;if(p==='/day-1'||p==='/presenter-1')return <Deck day={1}/>;if(p==='/day-2'||p==='/presenter-2')return <Deck day={2}/>;if(p==='/submit')return <Submit/>;if(p==='/submissions')return <Review/>;return <Shell><div className="home"><b>HUMAN SCHOOL</b><h1>Corporate AI Workshop</h1><a href="/day-1">Day 1 · Ground</a><a href="/day-2">Day 2 · Apply</a></div></Shell>}createRoot(document.getElementById('root')).render(<App/>);
